### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by jannle** [softlayer/softlayer-java#25]
I got java.lang.OutOfMemoryError: PermGen space every time when List<Guest> guests = service.getObject().getVirtualGuests() is called. Below is my code

public static List<Guest> getVirtualGuests() {
        String userName = <UserName>;
        String passWord = <password>;
        client = new RestApiClient().withCredentials(userName, passWord);
        Account.Service service = Account.service(client);
        service.withMask().virtualGuests().operatingSystem();
        service.withMask().virtualGuests().datacenter();
        service.withMask().virtualGuests().powerState();
        List<Guest> guests = service.getObject().getVirtualGuests();
        return guests;
    }

Anyone else has the issue? Stacktrace attached.

Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:1817)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:872)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1325)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1204)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:390)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:371)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:673)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:480)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:306)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:241)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:88)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:70)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3217)
	at java.lang.Class.getAnnotation(Class.java:3176)
	at java.lang.Package.getAnnotation(Package.java:388)
	at com.softlayer.api.json.GsonJsonMarshallerFactory.<clinit>(GsonJsonMarshallerFactory.java:51)
	at com.softlayer.api.json.JsonMarshallerFactory.getDefault(JsonMarshallerFactory.java:28)
	at com.softlayer.api.json.JsonMarshallerFactory.getDefault(JsonMarshallerFactory.java:17)
	at com.softlayer.api.RestApiClient.getJsonMarshallerFactory(RestApiClient.java:98)
	at com.softlayer.api.RestApiClient$ServiceProxy.logAndHandleResponse(RestApiClient.java:256)
	at com.softlayer.api.RestApiClient$ServiceProxy.invokeService(RestApiClient.java:300)
	at com.softlayer.api.RestApiClient$ServiceProxy.invoke(RestApiClient.java:466)
	at com.sun.proxy.$Proxy5.getObject(Unknown Source)
	at ....SoftLayerUtil.getVirtualGuests(SoftLayerUtil.java:57)

**Comment by jannle** [comment]
JAVA_OPTS="$JAVA_OPTS -Xms2048m -Xmx8144m -Xint"

**Comment by critix** [comment]
Same problem, can't get a list of VMs

**Comment by cretz** [comment]
You will have to increase your perm gen space or move to a more modern Java version that doesn't use perm gen space and will not have this problem.
